/* DELETANDO UM BANCO DE DADOS */

DROP DATABASE CADASTROS

/* CONTINUANDO ELABORAÇÃO DE QUERYS COMPLEXAS */

USE PROJETO

/* QUERY COM MUITOS DADOS DE VÁRIAS TABELAS, PORÉM SEM FILTRO */

SELECT C.NOME, C.EMAIL, E.RUA, E.BAIRRO, E.CIDADE, T.TIPO, T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE

SELECT NOME, CIDADE
FROM CLIENTE
INNER JOIN ENDERECO
ON IDCLIENTE = ID_CLIENTE

SELECT * FROM TELEFONE

/* QUERY COM MUITOS DADOS DE VÁRIAS TABELAS, COM FILTROS E PONTEIRAMENTO*/

SELECT C.NOME, C.SEXO, E.BAIRRO, E.CIDADE, T.TIPO, T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
WHERE SEXO = 'F'

/* QUERY COM MUITOS DADOS DE VÁRIAS TABELAS, COM FILTROS E PONTEIRAMENTO*/

SELECT C.NOME, C.SEXO, E.BAIRRO, E.CIDADE, T.TIPO, T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
WHERE SEXO = 'F' AND CIDADE = 'SÃO PAULO'

/* TOMAR CUIDADE COM QUERYS QUE USAM TABELA VERDADE, PORQUE FICA BEM CONFUSO QUANDO
SE USA TABELA VERDADE COM VÁRIAS CONDIÇÕES */

/* FUNÇÃO IFNULL 
FUNÇÃO - BLOCO DE PROGRAMAÇÃOP EM SQL - UMA FUNÇÃO PODE TER PARÂMETROS OU NÃO -
RESUME-SE A UM BLOCO DE CÓDIGO QUE RETORNA ALGUMA COISA, CONFORME DEFINIDO NA
PROPRIA FUNÇÃO
*/

SELECT	C.NOME, 
		ISNULL(C.EMAIL,'NÃO DECLARADO') AS EMAIL
FROM	CLIENTE C
		INNER JOIN ENDERECO E
ON		C.IDCLIENTE = E.ID_CLIENTE


SELECT * FROM CLIENTE

/* QUERY COM MUITOS DADOS DE VÁRIAS TABELAS, COM FILTROS E PONTEIRAMENTO - CRIANDO VIEWS */

CREATE VIEW RELATORIO AS
SELECT C.NOME, C.EMAIL, E.RUA, E.BAIRRO, E.CIDADE, T.TIPO, T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE

/* EXIBINDO A VIEW */

SELECT * FROM RELATORIO

/* DELETANDO A VIEW */

DROP VIEW RELATORIO

/* CRIANDO NOVAMENTE A VIEW */

CREATE VIEW RELATORIO AS
SELECT	C.NOME,
		ISNULL(C.EMAIL,'NÃO DECLARADO') AS "E-MAIL", 
		E.RUA, 
		E.BAIRRO, 
		E.CIDADE, 
		T.TIPO, 
		T.NUMERO
FROM	CLIENTE C
INNER JOIN ENDERECO E
ON		C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON		C.IDCLIENTE = T.ID_CLIENTE

/* EXIBINDO A VIEW */

SELECT * FROM RELATORIO

/* EXIBINDO A VIEW COM FILTRO*/

SELECT * FROM RELATORIO
WHERE TIPO = 'CEL'