/* ALTERANDO ESTRUTURA DE UMA TABELA - MAIS COMANDOS */

USE CURSOS


CREATE TABLE EXEMPLO(
	COLUNA1 VARCHAR(30),
	COLUNA2 VARCHAR(30)
)

INSERT INTO EXEMPLO VALUES('RICARDO', 'GIOVANA')

SELECT * FROM EXEMPLO


/* ADICIONANDO COLUNA NA TABELA */
ALTER TABLE EXEMPLO
ADD COLUNA VARCHAR(30)

/* ADICIONANDO TIPAGEM NA COLUNA(ULTIMA DA TABELA) */
SELECT * FROM EXEMPLO

ALTER TABLE EXEMPLO
ADD PRIMARY KEY(COLUNA)

/* ADICIONANDO COLUNA NA TABELA DEPOIS DA COLUNA 2 */

ALTER TABLE EXEMPLO
ADD COLUNA3 INT
AFTER COLUNA2

/* ADICIONANDO UMA FOREIGN KEY A UMA COLUNA */

ALTER TABLE EXEMPLO
ADD FOREIGN KEY(COLUNA)
REFERENCES PESSOA(COLUNA1)

/* RENOMEANDO UMA TABELA - DE EXEMPLO PARA PESSOA */

EXEC sp_rename EXEMPLO, PESSOA