USE PROJETO

/* INSERINDO NOVA COLUNA COM SALARIO DOS CLIENTES */

SELECT * FROM CLIENTE

ALTER TABLE CLIENTE ADD SALARIO FLOAT

UPDATE CLIENTE
SET SALARIO = 25000.00
WHERE IDCLIENTE = 1

UPDATE CLIENTE
SET SALARIO = 3750.00
WHERE IDCLIENTE = 2

UPDATE CLIENTE
SET SALARIO = 1500.00
WHERE IDCLIENTE = 3

UPDATE CLIENTE
SET SALARIO = 4600.00
WHERE IDCLIENTE = 4

UPDATE CLIENTE
SET SALARIO = 1450.00
WHERE IDCLIENTE = 5

SELECT * FROM CLIENTE

/* DELETANDO REGISTRO DE UMA TABELA */

DELETE FROM USUARIO
WHERE IDUSUARIO = 1

/* INSERINDO REGISTRO NA TABELA CLIENTE E LOGO APÓS, DELETANDO O REGISTRO 6 */

INSERT INTO CLIENTE VALUES('MARCIA','F','marcia@gmail.com','521869789',GETDATE(),8560.00)

SELECT * FROM CLIENTE

DELETE FROM CLIENTE
WHERE IDCLIENTE = 6