/* STORED PROCEDURE */

USE PROJETO

/* STORED PROCEDURE - CRIANDO UMA STORED PROCEDURE */

CREATE PROCEDURE NOME
AS
SELECT * FROM CLIENTE

/* STORED PROCEDURE - CHAMANDO UMA STORED PROCEDURE */

EXEC NOME

/* STORED PROCEDURE - FAZER CONTAS COM STORED PROCEDURE  */

CREATE PROCEDURE SOMA
AS
SELECT 10+10

EXEC SOMA

/*CRIANDO UMA NOVA DATABASE E NOVAS TABELAS */

CREATE DATABASE CURSOS

CREATE TABLE CURSO(
	IDCURSO INT PRIMARY KEY IDENTITY(1,1),
	NOME VARCHAR(50) NOT NULL,
	HORAS INT NOT NULL,
	PRECO FLOAT
)

INSERT INTO CURSO VALUES('JAVA',30,500.00)
INSERT INTO CURSO VALUES('JAVASCRIPT',50,1500.00)
INSERT INTO CURSO VALUES('C++',100,2500.00)

SELECT * FROM CURSO

/*CRIANDO UMA SPROCEDURE PARA INSERÇÃO DE DADOS NA DATABASE CURSOS E NA TABELA CURSO */

CREATE PROCEDURE ST_INSERCAO(@CURSO AS VARCHAR(30),@HORAS AS INT,@PRECO AS FLOAT)
AS
INSERT INTO CURSO VALUES(@CURSO,@HORAS,@PRECO)

/*INSERINDO DADOS NA TABELA ATRAVÉS DA PROCEDURE - IMPORTANTE
LEMBRAR QUE NA EXECUÇÃO DA PROCEDURE NO SQL SERVER NÃO PRECISA
COLOCAR PARENTESES NOS PARÂMETROS. SÓ PRECISA COLOCAR:
EXEC NOMEDAPROCEDURE PARÂMETROS E EXECUTAR, CONFORME ABAIXO
*/

SELECT * FROM CURSO

EXEC ST_INSERCAO BIPYTHON,40,1500.00

/* DELETANDO DATABASES */

DROP DATABASE Banco

DROP DATABASE DIEGO

DROP DATABASE LOJA
