/* CRIAÇÃO DE UM BANCO DEMONSTRATIVO NOME: PROJETO */

CREATE DATABASE PROJETO

USE PROJETO

CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY IDENTITY(1,1),
	NOME VARCHAR(30) NOT NULL,
	SEXO CHAR(2) CHECK(SEXO IN('M','F')),
	EMAIL VARCHAR(50) UNIQUE,
	CPF VARCHAR(15) UNIQUE
)

CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY IDENTITY(1,1),
	RUA VARCHAR(30) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	ID_CLIENTE INT UNIQUE,
	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
)

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY IDENTITY(1,1),
	TIPO CHAR(3) CHECK(TIPO IN('RES','CEL','COM')),
	NUMERO VARCHAR(10) NOT NULL,
	ID_CLIENTE INT,
	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
)

/*ALGUMAS OBSERVAÇÕES SOBRE A CONSTRUÇÃO DO BANCO ACIMA
	O BANCO FOI IDEALIZADO A PARTIR DE ALGUMAS REGRAS DE NÉGOCIO, COMO SEGUE:
	1-O USUÁRIO PODERÁ CADASTRAR SOMENTE 1 ENDEREÇO;
	2-o USUÁRIO PODERÁ CADASTRAR MAIS DE 1 TELEFONE;

CONSEQUÊNCIAS DAS REGRAS DE NEGÓCIOS ACIMA
	1-NA TABELA ENDEREÇO A CHAVE ESTRANGEIRA FOI IDENTIFICADA COMO "UNIQUE",
	POIS DESSA FORMA, CASO O USUÁRIO QUEIRA CADASTRAR MAIS DE 1 ENDEREÇO
	O BANCO IMPEDIRÁ, JÁ QUE O COMANDO NA TABELA ENDEREÇO SÓ PARA TER 1
	NUMERO. SE UM MESMO CLIENTE TENTAR SE CADASTRAR COM ENDEREÇOS DIFERENTES,
	O BANCO DETECTARÁ O MESMO E NÃO DEIXARÁ ENTRAR O REGISTRO.
*/