USE PROJETO

/* INSERÇÃO DE DADOS NO DATABASE PROJETO - TABELA CLIENTES, ENDEREÇO e TELEFONE */
/* INSERINDO NA TABELA CLIENTES */

INSERT INTO CLIENTE VALUES('RICARDO SOARES','M','risoares@yahoo.com.br','048139418')
INSERT INTO CLIENTE VALUES('GIOVANA SOARES','F','gisoares@yahoo.com.br','168139418')
INSERT INTO CLIENTE VALUES('MARIA SOARES','F',NULL,'234139418')
INSERT INTO CLIENTE VALUES('DANIEL SOARES','M','daniels@yahoo.com.br','139139456')

SELECT * FROM CLIENTE

/* INSERINDO NA TABELA ENDEREÇO */

INSERT INTO ENDERECO VALUES('RUA ANTONIO AMBUBA, 80','JD MUNHOZ','SÃO PAULO','SP',2)
INSERT INTO ENDERECO VALUES('RUA A, 90','JD ABC','RIO JANEIRO','RJ',3)
INSERT INTO ENDERECO VALUES('RUA B, 100','JD CDB','BELO HORIZONTE','MG',4)
INSERT INTO ENDERECO VALUES('RUA ALFA, 105','JD GBM','SÃO PAULO','SP',1)

SELECT * FROM ENDERECO

/* INSERINDO NA TABELA TELEFONE */

INSERT INTO TELEFONE VALUES('CEL','997149142','2')
INSERT INTO TELEFONE VALUES('RES','929149142','2')
INSERT INTO TELEFONE VALUES('CEL','997168142','3')
INSERT INTO TELEFONE VALUES('COM','997149142','3')
INSERT INTO TELEFONE VALUES('CEL','997145142','4')
INSERT INTO TELEFONE VALUES('CEL','997149142','1')
INSERT INTO TELEFONE VALUES('RES','987149138','1')

SELECT * FROM TELEFONE

